name: Submit Lab1
on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  submit:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'submit lab1')
    steps:
      - name: Notify server for submission
        run: |
          curl -X POST http://52.14.160.80/submit-lab \
          -H "Content-Type: application/json" \
          -d '{"student_repo": "${{ github.repository }}", "commit_id": "${{ github.sha }}"}'
